# BOT TOKEN CONFIG / CONFIG DE EL TOKEN DEL BOT
TOKEN: "INSERT-YOUR-DISCORD-BOT-TOKEN-HERE" # GET YOUR BOT TOKEN IN/OBTENGA EL TOKEN DE SU BOT EN: https://discord.com/developers/applications

# BOT ACTIVITY CONFIG / CONFIG DE LA ACTIVIDAD DEL BOT
ACTIVITY:
  TYPE: "PLAYING" # PLAYING (JUGANDO a %ACTIVITY%) COMPETING (COMPITIENDO en %ACTIVITY%), LISTENING (ESCUCHANDO %ACTIVITY%), WATCHING (MIRANDO %ACTIVITY%), STREAMING (EN STREAM de %ACTIVITY%), (CUSTOM = Don't type / Sin tipo de actividad)
  STATUS: "ONLINE" # DO_NOT_DISTURB (NO MOLESTAR), IDLE (AUSENTE), INVISIBLE (INVISIBLE), (OFFLINE (DESCONECTADO) = Bot don't start / El bot no inicia)
  ACTIVITY: "spacehcf.us" # (CUSTOM Ex/Ej: Playing Bunkers-01 on spacehcf.us / Jugando a Bunkers-01 en spacehcf.us)
  STREAM_URL: "https://twitch.tv/liteclubdevelopment" # ONLY WORKS IF ACTIVITY TYPE IS "STREAMING" / SOLO FUNCIONA SI ACTIVITY TYPE ES "STREAMING"